<robot name="my_base_link_floor" xmlns:xacro="http://www.ros.org/wiki/xacro"  >
    <xacro:property name="PI" value="3.141"/>
    <!-- 宏:黑色设置 -->
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>
    <xacro:property name="footprint_radius" value="0.001" />
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}" />
            </geometry>
        </visual>
    </link>
    <xacro:property name="base_link_width" value="0.600" />
    <xacro:property name="base_link_length" value="0.400" />
    <xacro:property name="base_link_height" value="0.050" />
    <xacro:property name="earth_space" value="0.1325" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_link_length} ${base_link_width} ${base_link_height}" />
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>
    </link>
    <joint name="base_link2base_footprint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0.3 0 ${earth_space + base_link_length / 2 }" />
    </joint>

    <xacro:property name="footrest_link_width" value="0.250" />
    <xacro:property name="footrest_link_length" value="0.260" />
    <xacro:property name="footrest_link_height" value="0.050" />

    <link name="footrest_link">
        <visual>
            <geometry>
                <box size="${footrest_link_length} ${footrest_link_width} ${footrest_link_height}" />
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="footrest2base_link" type="fixed">
        <parent link="base_link" />
        <child link="footrest_link" />
        <origin xyz="0.320 0 0" rpy="0 0 0"/>
    </joint>

    <xacro:property name="wheel_radius" value="0.1325" />
    <xacro:property name="wheel_length" value="0.05" />

    <xacro:macro name="add_wheels" params="name flag">
    <link name="${name}_wheel">
        <visual>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}" />
          </geometry>
          <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
          <material name="black" />
        </visual>
    </link>

    <joint name="${name}_wheel2base_link" type="continuous">
        <parent link="base_link" />
        <child link="${name}_wheel" />
        <origin xyz="0 ${flag * base_link_width} ${-(earth_space + base_link_length / 2 - wheel_radius) }" />
        <axis xyz="0 1 0" />
      </joint>
    </xacro:macro>
    <xacro:add_wheels name="left" flag="1" />
    <xacro:add_wheels name="right" flag="-1" />

    <xacro:property name="front_wheel_radius" value="0.0075" /> 
    <xacro:property name="front_wheel_length" value="0.05" />
    <xacro:macro name="add_front_wheel" params="name flag" >
      <link name="${name}_wheel">
        <visual>
            <geometry>
                <sphere radius="${front_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black" />
        </visual>
      </link>

      <joint name="${name}_wheel2base_link" type="continuous">
          <parent link="base_link" />
          <child link="${name}_wheel" />
          <origin xyz="${flag * (base_link_width - front_wheel_radius)} 0 ${-(base_link_length / 2 + earth_space / 2)}" />
          <axis xyz="1 1 1" />
      </joint>
    </xacro:macro>

    <xacro:add_front_wheel name="front" flag="1" />
    <xacro:add_front_wheel name="back" flag="-1" />
    </robot>



